---

- name: Install unzip
  apt: name=unzip state=present

- name: Install python-pip
  apt: name=python-pip

- name: Install jq
  apt: name=jq state=present

- name: Install required pip packages
  pip: name={{ item }} state=present
  with_items: "{{ consul_pip_pkgs }}"

- name: Create consul directories
  file: dest={{ item }} state=directory
  with_items: 
    - "{{ consul_work_dir }}"
    - "{{ consul_conf_dir }}"
    - "{{ consul_bin_dir }}"
    - "{{ consul_log_dir }}"
    - "{{ consul_scripts_dir }}"

- name: Get consul package checksum file
  get_url: url={{ consul_checksum_file_url }} dest={{ consul_work_dir }}

- name: Get checksum of consul package
  shell: grep {{ consul_pkg }} {{ consul_work_dir }}/{{ consul_checksum_file }}
  register: chksum

- name: Download consul package
  get_url: url={{ consul_pkg_url }} dest={{ consul_work_dir }}/{{ consul_pkg }} checksum="sha256:{{ chksum.stdout.split(' ')|first }}"

- name: Install consul
  unarchive: src={{ consul_work_dir }}/{{ consul_pkg }} dest={{ consul_bin_dir }} copy=no

- name: Install consul scripts
  copy: src={{ item }} dest={{ consul_scripts_dir }}/{{ item }} mode=0755
  with_items: "{{ consul_scripts }}"

#- name: Create watchers service definition
#  template: src=watchers.json.j2 dest={{ consul_conf_dir }}/watchers.json mode=0644

- name: Create consul upstart script
  template: src=consul.upstart.conf.j2 dest=/etc/init/consul.conf mode=0644

#- name: Create redeploy_service script
#  template: src=redeploy_service.sh.j2 dest={{ consul_scripts_dir }}/redeploy_service.sh mode=0755

- name: Start consul
  service: name=consul pattern={{ consul_bin_dir }}/consul enabled=yes state=started 
